### ISSUE TITLE
nest_() and unnest_() are deprecated in next release of tidyr

### ISSUE THREAD

**Issue by jennybc** [juliasilge/widyr#26]
`tidyr::nest_()` and `tidyr::unnest_()` have been deprecated for some time and are defunct in dev tidyr, which is slated to become v1.0.0.

Here's what we see in revdep checks:

https://github.com/tidyverse/tidyr/blob/master/revdep/problems.md#widyr

I'm hoping that the recent updates in fuzzyjoin and the thread below give some good leads on how to adapt widyr. Let me know if I can be of help!

https://github.com/tidyverse/tidyr/issues/692#issuecomment-518422512

**Comment by juliasilge** [comment]
This has been fixed at some point. Thanks! 🙌
