### ISSUE TITLE
Feature Request - Parallel pairwise_* functions

### ISSUE THREAD

**Issue by storopoli** [juliasilge/widyr#33]
Could we have a parallel implementation of the `pairwise_*` functions?

This could be done with `furrr`, I guess...

**Comment by juliasilge** [comment]
Thank you so much for your patience on this! 🙌 

The operations that this package supports are all matrix-like, with a pattern of "tidy ➡️ wide ➡️ tidy". This isn't something that can be done in parallel directly as the entire matrix needs to be in memory for the transformation. Let us know if you have further thoughts!
