### ISSUE TITLE
Error in `colnames<-`(`*tmp*`, value = c("item1", "item2", "value")) 

### ISSUE THREAD

**Issue by michaelgaunt404** [juliasilge/widyr#35]
Hi, I'm getting this error when I run the following code after loading a number of packages that I need for my analysis:
`
library(magrittr)
library(textrecipes)
library(tidytext)
library(tidyverse)
library(tidymodels)
library(modeldata)
library(textstem)
library(janitor)
library(ClusterR)
library(cluster)
library(widyr)

dat <- tidyr::tibble(group = rep(1:5, each = 2),
              letter = c("a", "b",
                         "a", "c",
                         "a", "c",
                         "b", "e",
                         "b", "f"))

# count the number of times two letters appear together
widyr::pairwise_count(dat, letter, group)`

The dat and pairwise count code works with an rstudio refresh but not after I load those packages.... I'm completely up-to-date on my package versions.

**Comment by juliasilge** [comment]
This is now fixed in the new widyr 0.1.5 that just went to CRAN:

``` r
library(tidyverse)
library(widyr)
dat <- tibble(group = rep(1:5, each = 2),
              letter = c("a", "b",
                         "a", "c",
                         "a", "c",
                         "b", "e",
                         "b", "f"))

pairwise_count(dat, letter, group)
#> # A tibble: 8 × 3
#>   item1 item2     n
#>   <chr> <chr> <dbl>
#> 1 b     a         1
#> 2 c     a         2
#> 3 a     b         1
#> 4 e     b         1
#> 5 f     b         1
#> 6 a     c         2
#> 7 b     e         1
#> 8 b     f         1
```

<sup>Created on 2022-09-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Thanks! 🙌
