### ISSUE TITLE
Call to deprecated `distinct_` in `pairwise_count.R`

### ISSUE THREAD

**Issue by aurelberra** [juliasilge/widyr#38]
As `pairwise_count.R` uses the deprecated `distinct_` function ([here](https://github.com/dgrtwo/widyr/blob/6312a8ef2990f6cd33464168133d8d03209a895e/R/pairwise_count.R#L55)), a warning is raised.

The warning consequently appears in `tidytext` (cf. this older [issue](https://github.com/juliasilge/tidytext/issues/179)), where I saw it.

**Comment by DataSciNet** [comment]
As noted in the text of the warning message, distinct_() has been replaced with dplyr::distinct(), and tbl_df() has been replaced with tibble::as_tibble().

**Comment by juliasilge** [comment]
This is fixed in the new widyr 0.1.5 that just went to CRAN. Thanks! 🙌
